config/routes.rb
Rails.application.routes.draw do
  root "films#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :film_casts
  has_many :casts, through: :film_casts
  has_many :film_trailers
  has_many :trailers, through: :film_trailers
  has_many :comments
  has_many :likes
  has_many :likers, through: :likes, source: :user

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film.html.erb
<div class="film">
  <div class="left-show">
    <%= link_to film_path(film), data: {turbo: false} do %>
      <%= image_tag(film.poster_image_url.present? && film.poster_image_url != "/global/images/jfdb_noimage.png" ? film.poster_image_url : asset_path('noimage.png'), class: "poster-image") %>
    <% end %>
  </div>
  <div class="right-show">
    <div class="title-show">
      <h2><%= link_to film.title, film_path(film) %></h2>
      <span class="release-date"><%= film.release_date %></span>
    </div>
    <div class="text-show">
      <p><%= film.description %></p>
    </div>
  </div>
</div>

app/views/films/index.html.erb
<%= render "shared/navbar" %>
<div class="index-main">
  <div class="curtain">
    <%= image_tag "curtain2.png", class: "curtain-image" %>
    <video id="opening-video" data: {turbo: false}>
      <source src="<%= asset_path('opening2.mp4') %>" type="video/mp4">
      Your browser does not support the video tag.
    </video>
    <div class="contents">
      <%= form_with(url: "#", method: "get", local: true, class: "main-search-form") do |form| %>
        <div class="top-content">
          <label>
            <%= form.check_box :search_title, {}, "1", "0" %>
            <span class="checkbox-label">タイトル</span>
          </label>
          <label>
            <%= form.check_box :search_cast, {}, "1", "0" %>
            <span class="checkbox-label">俳優名</span>
          </label>
          <label>
            <%= form.check_box :search_staff, {}, "1", "0" %>
            <span class="checkbox-label">スタッフ名</span>
          </label>
        </div>
        <div class="search-container">
        <%= form.text_field :q_cont, placeholder: "Search", class: "search-input" %>
        <%= form.submit "ホリック", class: "search-btn" %>
        </div>
      <% end %>
      <div class="bottom-content">
        <%= link_to "上映中", "#", class: "enter-buttin" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curtain</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="csrf-token" content="<%= form_authenticity_token %>">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hina+Mincho&display=swap" rel="stylesheet">
    <link rel="preload" href="<%= asset_path('application.css') %>" as="style">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="logo"><%= link_to image_tag("title2.png", class:"title-icon"), "/" %></div>
  <div class="menu" id="menu">
    <span><%= image_tag "menu2.png" %></span>
    <ul class="lists hidden" id="pull-down">
      <li class="top-list"><%= link_to "上映作品", "#" %></li>
      <%# <% if user_signed_in? %>
      <li class="second-list"><%= link_to "マイページ", "#" %></li>
      <li class="third-list"><%= link_to "ログアウト", "#", data: { turbo_method: :delete }%></li>
      <%# <% else %>
      <li class="fourth-list"><%= link_to "サインイン", "#" %></li>
      <li class="fifth-list"><%= link_to "ログイン", "#" %></li>
      <%# <% end %>
      <li class="dropdown">
        <div class="dropdown-content">
          <%= form_tag("#", method: "get", class: "search-form") do %>
            <input type="text" name="q" placeholder="Search" style="text-align: right;">
            <button type="submit">GO</button>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>